# docker-compose.yml

version: '3.8'

services:

  order-api:

    build: .

    container_name: yemek-siparis-api
    

    ports:
      - "5000:5000"
    
 
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development


